### ISSUE TITLE
Panic while processing wsdl

### ISSUE THREAD

**Issue by santegoeds** [fiorix/wsdl2go#17]
I'm trying to process the wsdl from https://testing.maventa.com/apis/v1.1/wsdl.  Unfortunately I'm seeing a panic:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6b6a40, 0xc42000c1b0)
        /home/vagrant/.local/share/umake/go/go-lang/src/runtime/panic.go:500 +0x1a1
maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).writeInterfaceFuncs(0xc4201f0720, 0x842940, 0xc4201773b0, 0xc4200ee000, 0xc42022ad01, 0xc420222aa0)
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:296 +0x900
maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).(maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo.writeInterfaceFuncs)-fm(0x842940, 0xc4201773b0, 0xc4200ee000, 0x0, 0x4)
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:137 +0x48
maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).encode(0xc4201f0720, 0x842940, 0xc420177340, 0xc4200ee000, 0xc420072a14, 0x1)
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:150 +0x3bc
maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).Encode(0xc4201f0720, 0xc4200ee000, 0xc4202076e0, 0x0)
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:91 +0xbe
main.decode(0x843480, 0xc42002c010, 0x0, 0x0, 0x863600, 0x15, 0x1e)
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/main.go:74 +0x3fc
main.main()
        /home/vagrant/dev/grpc-demo/src/maventa/vendor/github.com/fiorix/wsdl2go/main.go:53 +0x210
```

**Comment by fiorix** [comment]
I haven't done any functional test on this. Instead, fixed the crash and other minor things as per the commit message.
