### ISSUE TITLE
panic: interface conversion: http.RoundTripper is nil, not *http.Transport

### ISSUE THREAD

**Issue by Fank** [fiorix/wsdl2go#64]
Caused by e0dbfbafad158b1e6714655fc31b0bb0038ab8db

```bash
$ wsdl2go < search.wsdl > asd.go
panic: interface conversion: http.RoundTripper is nil, not *http.Transport

goroutine 1 [running]:
main.httpClient(...)
	/home/fkinder/go/src/github.com/fiorix/wsdl2go/main.go:99
main.main()
	/home/fkinder/go/src/github.com/fiorix/wsdl2go/main.go:53 +0x4f6
```

**Comment by adriantam** [comment]
We likely want to turn off InsecureSkipVerify

**Comment by turboezh** [comment]
https://github.com/fiorix/wsdl2go/pull/61#pullrequestreview-83416933
