### ISSUE TITLE
generate panic error nil pointer

### ISSUE THREAD

**Issue by r1se** [fiorix/wsdl2go#96]
Hi, i'm try genearet code form documental wsdl (https://api.reformagkh.ru/api_document_literal/wsdl)

But i'm get error:

```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6eba3b]
> 
> goroutine 1 [running]:
> github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).genGoOpStruct(0xc420168bb0, 0x94db80, 0xc4201579d0, 0xc42015e000, 0xc4202d4a00, 0x0, 0x0)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:1358 +0x11b
> github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).writeGoTypes(0xc420168bb0, 0x94db80, 0xc420156d90, 0xc42015e000, 0x0, 0x0)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:1110 +0x82f
> github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).(github.com/fiorix/wsdl2go/wsdlgo.writeGoTypes)-fm(0x94db80, 0xc420156d90, 0xc42015e000, 0x0, 0x0)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:208 +0x48
> github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).encode(0xc420168bb0, 0x94db80, 0xc420156d20, 0xc42015e000, 0x80, 0xc420128e40)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:220 +0x370
> github.com/fiorix/wsdl2go/wsdlgo.(*goEncoder).Encode(0xc420168bb0, 0xc42015e000, 0xc42027f1d0, 0x0)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:145 +0xa4
> main.codegen(0x94e680, 0xc42000e018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/main.go:86 +0x468
> main.main()
> 	/home/neroot/go/src/github.com/fiorix/wsdl2go/main.go:57 +0x3ce
> 
```

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by denysvitali** [comment]
Check out my PR #131
